const getTokensPrice = require('./getTokensPrice');
const getCirculatingSupply = require('./getCirculatingSupply');
const getTotalSupply = require('./getTotalSupply');
const getInflation = require('./getInflation');
const getChainMaintainers = require('./getChainMaintainers');
const getEscrowAddresses = require('./getEscrowAddresses');
const searchBlocks = require('./searchBlocks');
const searchTransactions = require('./searchTransactions');
const searchPolls = require('./searchPolls');
const searchUptimes = require('./searchUptimes');
const searchHeartbeats = require('./searchHeartbeats');
const getValidators = require('./getValidators');
const getValidatorsVotes = require('./getValidatorsVotes');
const getProposals = require('./getProposals');
const searchBatches = require('./searchBatches');
const searchDepositAddresses = require('./searchDepositAddresses');
const transfersStats = require('./transfersStats');
const transfersChart = require('./transfersChart');
const transfersCumulativeVolume = require('./transfersCumulativeVolume');
const transfersTotalVolume = require('./transfersTotalVolume');
const transfersTotalFee = require('./transfersTotalFee');
const transfersTotalActiveUsers = require('./transfersTotalActiveUsers');
const transfersTopUsers = require('./transfersTopUsers');
const searchTransfers = require('./searchTransfers');
const getTransferDataMapping = require('./getTransferDataMapping');
const interchainChart = require('./interchainChart');
const interchainTotalVolume = require('./interchainTotalVolume');
const interchainTotalFee = require('./interchainTotalFee');
const interchainTotalActiveUsers = require('./interchainTotalActiveUsers');
const getTVL = require('./getTVL');
const getLatestEventBlock = require('./getLatestEventBlock');

const test = async () => {
  await getTokensPrice();
  await getCirculatingSupply();
  await getTotalSupply();
  await getInflation();
  await getChainMaintainers();
  await getEscrowAddresses();
  await searchBlocks();
  await searchTransactions();
  await searchPolls();
  await searchUptimes();
  await searchHeartbeats();
  await getValidators();
  await getValidatorsVotes();
  await getProposals();
  await searchBatches();
  await searchDepositAddresses();
  await transfersStats();
  await transfersChart();
  await transfersCumulativeVolume();
  await transfersTotalVolume();
  await transfersTotalFee();
  await transfersTotalActiveUsers();
  await transfersTopUsers();
  await searchTransfers();
  await getTransferDataMapping();
  await interchainChart();
  await interchainTotalVolume();
  await interchainTotalFee();
  await interchainTotalActiveUsers();
  await getTVL();
  await getLatestEventBlock();
};

test();