#########################################
# Cosmos Desposit Address Configuration #
#########################################

mainnet:
  send_token:
    addresses:
      - "axelar1dv4u5k73pzqrxlzujxg3qp8kvc3pje7jtdvu72npnt5zhq05ejcsn5qme5"



testnet:
  send_token:
    addresses:
      - "axelar1dv4u5k73pzqrxlzujxg3qp8kvc3pje7jtdvu72npnt5zhq05ejcsn5qme5"



stagenet:
  send_token:
    addresses:
      - "axelar1dv4u5k73pzqrxlzujxg3qp8kvc3pje7jtdvu72npnt5zhq05ejcsn5qme5"