########################
# Supply Configuration #
########################

mainnet:
  max_supply: 1000000000
  initial_unlocked_percent: 2.5
  community_sale:
    total_unlock_percent: 2.5
    vesting_period: "month"
    vesting_start: "2022-09-27"
    vesting_until: "2023-01-27"
  community_programs:
    total_unlock_percent: 36
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  company_operations:
    total_unlock_percent: 12.5
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  backers:
    total_unlock_percent: 29.5
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2024-12-27"
  team:
    total_unlock_percent: 17
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2026-12-27"



testnet:
  max_supply: 1000000000
  initial_unlocked_percent: 0
  community_sale:
    total_unlock_percent: 0
    vesting_period: "month"
    vesting_start: "2022-09-27"
    vesting_until: "2023-01-27"
  community_programs:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  company_operations:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  backers:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2024-12-27"
  team:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2026-12-27"

stagenet:
  max_supply: 1000000000
  initial_unlocked_percent: 0
  community_sale:
    total_unlock_percent: 0
    vesting_period: "month"
    vesting_start: "2022-09-27"
    vesting_until: "2023-01-27"
  community_programs:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  company_operations:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-09-27"
    vesting_until: "2026-09-27"
  backers:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2024-12-27"
  team:
    total_unlock_percent: 0
    vesting_period: "day"
    vesting_start: "2022-12-27"
    vesting_until: "2026-12-27"