######################
# Tokens Information #
######################

ETH:
  coingecko_id: "ethereum"
  decimals: 18
BNB:
  coingecko_id: "binancecoin"
  decimals: 18
MATIC:
  coingecko_id: "matic-network"
  decimals: 18
AVAX:
  coingecko_id: "avalanche-2"
  decimals: 18
FTM:
  coingecko_id: "fantom"
  decimals: 18
GLMR:
  coingecko_id: "moonbeam"
  decimals: 18
DEV:
  redirect: "GLMR"
AURORA:
  coingecko_id: "aurora-near"
  decimals: 18
aETH:
  redirect: "ETH"
CELO:
  coingecko_id: "celo"
  decimals: 18
KAVA:
  coingecko_id: "kava"
  decimals: 18
FIL:
  coingecko_id: "filecoin"
  decimals: 18
AXL:
  coingecko_id: "axelar"
  decimals: 6
OSMO:
  coingecko_id: "osmosis"
  decimals: 6
ATOM:
  coingecko_id: "cosmos"
  decimals: 6
JUNO:
  coingecko_id: "juno-network"
  decimals: 6
NGM:
  coingecko_id: "e-money"
  decimals: 6
INJ:
  coingecko_id: "injective-protocol"
  decimals: 6
CRE:
  coingecko_id: "crescent-network"
  decimals: 6
KUJI:
  coingecko_id: "kujira"
  decimals: 6
SCRT:
  coingecko_id: "secret"
  decimals: 6
SEI:
  coingecko_id: "sei-network"
  decimals: 6
STARS:
  coingecko_id: "stargaze"
  decimals: 6
MNTL:
  coingecko_id: "assetmantle"
  decimals: 6
FET:
  coingecko_id: "fetch-ai"
  decimals: 6
KI:
  coingecko_id: "ki"
  decimals: 6
EVMOS:
  coingecko_id: "evmos"
  decimals: 6
AURA:
  coingecko_id: "aura-network"
  decimals: 6
CMDX:
  coingecko_id: "comdex"
  decimals: 6
XPRT:
  coingecko_id: "persistence"
  decimals: 6
REGEN:
  coingecko_id: "regen"
  decimals: 6
UMEE:
  coingecko_id: "umee"
  decimals: 6
BLD:
  coingecko_id: "agoric"
  decimals: 6
XPLA:
  coingecko_id: "xpla"
  decimals: 6
ACRE:
  coingecko_id: "arable-protocol"
  decimals: 6
STRD:
  coingecko_id: "stride"
  decimals: 6
SWTH:
  coingecko_id: "switcheo"
  decimals: 6
ODIN:
  coingecko_id: "odin-protocol"
  decimals: 6
SOMM:
  coingecko_id: "sommelier"
  decimals: 6
NTRN:
  coingecko_id: "neutron-1"
  decimals: 6
REBUS:
  coingecko_id: "rebus"
  decimals: 6
LUNA:
  coingecko_id: "terra-luna-2"
  decimals: 6
wAXL:
  redirect: "AXL"
WAXL:
  redirect: "AXL"
WBTC:
  coingecko_id: "wrapped-bitcoin"
  decimals: 8
axlWBTC:
  redirect: "WBTC"
axlBTC:
  redirect: "WBTC"
WETH:
  coingecko_id: "weth"
  decimals: 18
axlWETH:
  redirect: "WETH"
axlETH:
  redirect: "WETH"
WBNB:
  coingecko_id: "wbnb"
  decimals: 18
axlWBNB:
  redirect: "WBNB"
axlBNB:
  redirect: "WBNB"
WMATIC:
  coingecko_id: "wmatic"
  decimals: 18
axlWMATIC:
  redirect: "WMATIC"
axlMATIC:
  redirect: "WMATIC"
WAVAX:
  coingecko_id: "wrapped-avax"
  decimals: 18
axlWAVAX:
  redirect: "WAVAX"
axlAVAX:
  redirect: "WAVAX"
WFTM:
  coingecko_id: "wrapped-fantom"
  decimals: 18
axlWFTM:
  redirect: "WFTM"
axlFTM:
  redirect: "WFTM"
WGLMR:
  coingecko_id: "wrapped-moonbeam"
  decimals: 18
axlWGLMR:
  redirect: "WGLMR"
axlGLMR:
  redirect: "WGLMR"
WDEV:
  redirect: "WGLMR"
axlWDEV:
  redirect: "WGLMR"
axlDEV:
  redirect: "WGLMR"
WFIL:
  redirect: "FIL"
axlWFIL:
  redirect: "FIL"
axlFIL:
  redirect: "FIL"
USDC:
  coingecko_id: "usd-coin"
  default_price:
    usd: 1.00
  decimals: 6
axlUSDC:
  redirect: "USDC"
aUSDC:
  redirect: "USDC"
USDT:
  coingecko_id: "tether"
  default_price:
    usd: 1.00
  decimals: 6
axlUSDT:
  redirect: "USDT"
DAI:
  coingecko_id: "dai"
  default_price:
    usd: 1.00
  decimals: 18
axlDAI:
  redirect: "USDT"
BUSD:
  coingecko_id: "binance-usd"
  default_price:
    usd: 1.00
  decimals: 18
axlBUSD:
  redirect: "BUSD"
axlOSMO:
  redirect: "OSMO"
axlATOM:
  redirect: "ATOM"
axlJUNO:
  redirect: "JUNO"
axlSEI:
  redirect: "SEI"
axlSOMM:
  redirect: "SOMM"