######################
# Tokens Information #
######################

ETH:
  coingecko_id: "ethereum"
  decimals: 18
BNB:
  coingecko_id: "binancecoin"
  decimals: 18
MATIC:
  coingecko_id: "matic-network"
  decimals: 18
AVAX:
  coingecko_id: "avalanche-2"
  decimals: 18
FTM:
  coingecko_id: "fantom"
  decimals: 18
GLMR:
  coingecko_id: "moonbeam"
  decimals: 18
DEV:
  redirect: "GLMR"
AURORA:
  coingecko_id: "aurora-near"
  decimals: 18
ARB:
  coingecko_id: "arbitrum"
  decimals: 18
MNT:
  coingecko_id: "mantle"
  decimals: 18
aETH:
  redirect: "ETH"
CELO:
  coingecko_id: "celo"
  decimals: 18
KAVA:
  coingecko_id: "kava"
  decimals: 18
FIL:
  coingecko_id: "filecoin"
  decimals: 18
CFG:
  coingecko_id: "centrifuge"
  decimals: 18
ALGL:
  redirect: "CFG"
IMX:
  coingecko_id: "immutable-x"
  decimals: 18
TIMX:
  redirect: "IMX"
AXL:
  coingecko_id: "axelar"
  decimals: 6
OSMO:
  coingecko_id: "osmosis"
  decimals: 6
ATOM:
  coingecko_id: "cosmos"
  decimals: 6
JUNO:
  coingecko_id: "juno-network"
  decimals: 6
NGM:
  coingecko_id: "e-money"
  decimals: 6
INJ:
  coingecko_id: "injective-protocol"
  decimals: 6
CRE:
  coingecko_id: "crescent-network"
  decimals: 6
KUJI:
  coingecko_id: "kujira"
  decimals: 6
SCRT:
  coingecko_id: "secret"
  decimals: 6
SEI:
  coingecko_id: "sei-network"
  decimals: 6
STARS:
  coingecko_id: "stargaze"
  decimals: 6
MNTL:
  coingecko_id: "assetmantle"
  decimals: 6
FET:
  coingecko_id: "fetch-ai"
  decimals: 6
KI:
  coingecko_id: "ki"
  decimals: 6
EVMOS:
  coingecko_id: "evmos"
  decimals: 6
AURA:
  coingecko_id: "aura-network"
  decimals: 6
CMDX:
  coingecko_id: "comdex"
  decimals: 6
XPRT:
  coingecko_id: "persistence"
  decimals: 6
REGEN:
  coingecko_id: "regen"
  decimals: 6
UMEE:
  coingecko_id: "umee"
  decimals: 6
BLD:
  coingecko_id: "agoric"
  decimals: 6
XPLA:
  coingecko_id: "xpla"
  decimals: 6
ACRE:
  coingecko_id: "arable-protocol"
  decimals: 6
STRD:
  coingecko_id: "stride"
  decimals: 6
SWTH:
  coingecko_id: "switcheo"
  decimals: 6
XION:
  coingecko_id: "switcheo"
  decimals: 6
ODIN:
  coingecko_id: "odin-protocol"
  decimals: 6
SOMM:
  coingecko_id: "sommelier"
  decimals: 6
NTRN:
  coingecko_id: "neutron-1"
  decimals: 6
REBUS:
  coingecko_id: "rebus"
  decimals: 6
IXO:
  coingecko_id: "ixo"
  decimals: 6
ARCH:
  coingecko_id: "archway"
  decimals: 6
HASH:
  coingecko_id: "provenance"
  default_price:
    usd: 0.02
  decimals: 6
TORI:
  coingecko_id: "teritori"
  decimals: 6
ISLM:
  coingecko_id: "islamiccoin"
  default_price:
    usd: 0.01
  decimals: 6
TIA:
  coingecko_id: "celestia"
  decimals: 6
axlTIA:
  redirect: "TIA"
WHALE:
  coingecko_id: "white-whale"
  decimals: 6
UST:
  coingecko_id: "terrausd"
USTC:
  redirect: "UST"
LUNA:
  coingecko_id: "terra-luna"
  decimals: 6
LUNAC:
  redirect: "LUNA"
wAXL:
  redirect: "AXL"
WAXL:
  redirect: "AXL"
WBTC:
  coingecko_id: "wrapped-bitcoin"
  decimals: 8
axlWBTC:
  redirect: "WBTC"
axlBTC:
  redirect: "WBTC"
WETH:
  coingecko_id: "weth"
  decimals: 18
axlWETH:
  redirect: "WETH"
axlETH:
  redirect: "WETH"
stETH:
  coingecko_id: "staked-ether"
  decimals: 18
axlSTETH:
  redirect: "stETH"
wstETH:
  coingecko_id: "staked-ether"
  decimals: 18
axl-wstETH:
  redirect: "wstETH"
cbETH:
  coingecko_id: "coinbase-wrapped-staked-eth"
  decimals: 18
frxETH:
  coingecko_id: "frax-ether"
  decimals: 18
sfrxETH:
  coingecko_id: "staked-frax-ether"
  decimals: 18
rETH:
  coingecko_id: "rocket-pool-eth"
  decimals: 18
yieldETH:
  coingecko_id: "weth"
  decimals: 18
WBNB:
  coingecko_id: "wbnb"
  decimals: 18
axlWBNB:
  redirect: "WBNB"
axlBNB:
  redirect: "WBNB"
stkBNB:
  coingecko_id: "pstake-staked-bnb"
  decimals: 18
WMATIC:
  coingecko_id: "wmatic"
  decimals: 18
axlWMATIC:
  redirect: "WMATIC"
axlMATIC:
  redirect: "WMATIC"
WAVAX:
  coingecko_id: "wrapped-avax"
  decimals: 18
axlWAVAX:
  redirect: "WAVAX"
axlAVAX:
  redirect: "WAVAX"
WFTM:
  coingecko_id: "wrapped-fantom"
  decimals: 18
axlWFTM:
  redirect: "WFTM"
axlFTM:
  redirect: "WFTM"
WGLMR:
  coingecko_id: "wrapped-moonbeam"
  decimals: 18
axlWGLMR:
  redirect: "WGLMR"
axlGLMR:
  redirect: "WGLMR"
WDEV:
  redirect: "WGLMR"
axlWDEV:
  redirect: "WGLMR"
axlDEV:
  redirect: "WGLMR"
WFIL:
  redirect: "FIL"
axlWFIL:
  redirect: "FIL"
axlFIL:
  redirect: "FIL"
USDC:
  coingecko_id: "usd-coin"
  default_price:
    usd: 1.00
  decimals: 6
axlUSDC:
  redirect: "USDC"
aUSDC:
  redirect: "USDC"
USDT:
  coingecko_id: "tether"
  default_price:
    usd: 1.00
  decimals: 6
axlUSDT:
  redirect: "USDT"
DAI:
  coingecko_id: "dai"
  default_price:
    usd: 1.00
  decimals: 18
axlDAI:
  redirect: "DAI"
BUSD:
  coingecko_id: "binance-usd"
  default_price:
    usd: 1.00
  decimals: 18
axlBUSD:
  redirect: "BUSD"
FRAX:
  coingecko_id: "frax"
  default_price:
    usd: 1.00
  decimals: 18
axlFRAX:
  redirect: "FRAX"
cUSD:
  coingecko_id: "celo-dollar"
  default_price:
    usd: 1.00
  decimals: 18
YieldUSD:
  coingecko_id: "tether"
  default_price:
    usd: 1.00
  decimals: 18
axlYieldUSD:
  redirect: "YieldUSD"
wUSDM:
  coingecko_id: "mountain-protocol-usdm"
  default_price:
    usd: 1.00
  decimals: 18
EEUR:
  coingecko_id: "e-money-eur"
  decimals: 18
LINK:
  coingecko_id: "chainlink"
  decimals: 18
axlLINK:
  redirect: "LINK"
UNI:
  coingecko_id: "uniswap"
  decimals: 18
axlUNI:
  redirect: "UNI"
AAVE:
  coingecko_id: "aave"
  decimals: 18
axlAAVE:
  redirect: "AAVE"
MKR:
  coingecko_id: "maker"
  decimals: 18
axlMKR:
  redirect: "MKR"
SHIB:
  coingecko_id: "shiba-inu"
  decimals: 18
axlSHIB:
  redirect: "SHIB"
APE:
  coingecko_id: "apecoin"
  decimals: 18
axlAPE:
  redirect: "APE"
AXS:
  coingecko_id: "axie-infinity"
  decimals: 18
axlAXS:
  redirect: "AXS"
RAI:
  coingecko_id: "rai"
  decimals: 18
axlRAI:
  redirect: "RAI"
XCN:
  coingecko_id: "chain-2"
  decimals: 18
axlXCN:
  redirect: "XCN"
PEPE:
  coingecko_id: "pepe"
  decimals: 18
axlPEPE:
  redirect: "PEPE"
MPX:
  coingecko_id: "mpx"
  decimals: 18
WMAI:
  coingecko_id: "mimatic"
  decimals: 18
axlWMAI:
  redirect: "WMAI"
ERN:
  coingecko_id: "ethos-reserve-note"
  decimals: 18
stERN:
  redirect: "ERN"
LQDR:
  coingecko_id: "liquiddriver"
  decimals: 18
axlLQDR:
  redirect: "LQDR"
WDOGE:
  coingecko_id: "dogecoin"
  decimals: 18
axlWDOGE:
  redirect: "WDOGE"
HZN:
  coingecko_id: "horizon-protocol"
  decimals: 18
DEUS:
  coingecko_id: "deus-finance-2"
  decimals: 18
axlDEUS:
  redirect: "DEUS"
GDX:
  coingecko_id: "gdx-token"
  decimals: 18
GRAIN:
  coingecko_id: "granary"
  decimals: 18
axlGRAIN:
  redirect: "GRAIN"
KNC:
  coingecko_id: "kyber-network-crystal"
  decimals: 18
axlKNC:
  redirect: "KNC"
OATH:
  coingecko_id: "oath"
  decimals: 18
ORBS:
  coingecko_id: "orbs"
  decimals: 18
POLS:
  coingecko_id: "polkastarter"
  decimals: 18
RING:
  coingecko_id: "onering"
  decimals: 18
SONNE:
  coingecko_id: "sonne-finance"
  decimals: 18
ZYB:
  coingecko_id: "zyberswap"
  decimals: 18
VELA:
  coingecko_id: "vela-token"
  decimals: 18
ARX:
  coingecko_id: "arbitrum-exchange"
  decimals: 18
VEXT:
  coingecko_id: "veloce-vext"
  decimals: 18
OVN:
  coingecko_id: "overnight"
  default_price:
    usd: 0.01
  decimals: 18
EUROC:
  coingecko_id: "euro-coin"
  decimals: 6
axlEUROC:
  redirect: "EUROC"
BAL:
  coingecko_id: "balancer"
  decimals: 18
axlBAL:
  redirect: "BAL"
KTC:
  coingecko_id: "ktx-finance"
axlKTC:
  redirect: "KTC"
stATOM:
  coingecko_id: "stride-staked-atom"
  decimals: 6
DOT:
  coingecko_id: "polkadot"
  decimals: 10
xcDOT:
  redirect: "DOT"
axlDOT:
  redirect: "DOT"
axlOSMO:
  redirect: "OSMO"
axlATOM:
  redirect: "ATOM"
axlJUNO:
  redirect: "JUNO"
axlSEI:
  redirect: "SEI"
axlSOMM:
  redirect: "SOMM"



uaxl:
  redirect: "AXL"
uusdc:
  redirect: "USDC"
uusdt:
  redirect: "USDT"
dai-wei:
  redirect: "DAI"
busd-wei:
  redirect: "BUSD"
frax-wei:
  redirect: "FRAX"
cusd-wei:
  redirect: "CUSD"
yieldusd-wei:
  redirect: "YieldUSD"
wbtc-satoshi:
  redirect: "WBTC"
eth-wei:
  redirect: "ETH"
weth-wei:
  redirect: "WETH"
steth-wei:
  redirect: "stETH"
wsteth-wei:
  redirect: "wstETH"
cbeth-wei:
  redirect: "cbETH"
frxeth-wei:
  redirect: "frxETH"
sfrxeth-wei:
  redirect: "sfrxETH"
reth-wei:
  redirect: "rETH"
yieldeth-wei:
  redirect: "yieldETH"
bnb-wei:
  redirect: "BNB"
wbnb-wei:
  redirect: "WBNB"
stkbnb-wei:
  redirect: "stkBNB"
matic-wei:
  redirect: "MATIC"
wmatic-wei:
  redirect: "WMATIC"
avax-wei:
  redirect: "AVAX"
wavax-wei:
  redirect: "WAVAX"
ftm-wei:
  redirect: "FTM"
wftm-wei:
  redirect: "WFTM"
glmr-wei:
  redirect: "GLMR"
wglmr-wei:
  redirect: "WGLMR"
dev-wei:
  redirect: "DEV"
arb-wei:
  redirect: "ARB"
fil-wei:
  redirect: "FIL"
wfil-wei:
  redirect: "WFIL"
celo-wei:
  redirect: "CELO"
link-wei:
  redirect: "LINK"
uni-wei:
  redirect: "UNI"
aave-wei:
  redirect: "AAVE"
mkr-wei:
  redirect: "MKR"
shib-wei:
  redirect: "SHIB"
ape-wei:
  redirect: "APE"
axs-wei:
  redirect: "AXS"
rai-wei:
  redirect: "RAI"
xcn-wei:
  redirect: "XCN"
pepe-wei:
  redirect: "PEPE"
mpx-wei:
  redirect: "MPX"
wmai-wei:
  redirect: "WMAI"
ern-wei:
  redirect: "ERN"
stern-wei:
  redirect: "stERN"
lqdr-wei:
  redirect: "LQDR"
wdoge-wei:
  redirect: "WDOGE"
hzn-wei:
  redirect: "HZN"
deus-wei:
  redirect: "DEUS"
gdx-wei:
  redirect: "GDX"
grain-wei:
  redirect: "GRAIN"
knc-wei:
  redirect: "KNC"
oath-wei:
  redirect: "OAUTH"
orbs-wei:
  redirect: "ORBS"
pols-wei:
  redirect: "POLS"
ring-wei:
  redirect: "RING"
sonne-wei:
  redirect: "SONNE"
zyb-wei:
  redirect: "ZYB"
vela-wei:
  redirect: "VELA"
arx-wei:
  redirect: "ARX"
vext-wei:
  redirect: "VEXT"
ovn-wei:
  redirect: "OVN"
ueuroc:
  redirect: "EUROC"
bal-wei:
  redirect: "BAL"
ktc-wei:
  redirect: "KTC"
uosmo:
  redirect: "OSMO"
uatom:
  redirect: "ATOM"
ujuno:
  redirect: "JUNO"
usei:
  redirect: "SEI"
ukuji:
  redirect: "KUJI"
ungm:
  redirect: "NGM"
eeur:
  redirect: "EEUR"
uumee:
  redirect: "UMEE"
ustrd:
  redirect: "STRD"
stuatom:
  redirect: "stATOM"
usomm:
  redirect: "SOMM"
utia:
  redirect: "TIA"
dot-planck:
  redirect: "DOT"
uusd:
  redirect: "USTC"
uluna:
  redirect: "LUNAC"
uausdc:
  redirect: "aUSDC"