general_indexer_url = "https://search-stagenet-general-3gart7zrqfgjiut372l5pougtm.us-east-2.es.amazonaws.com"
general_indexer_username = "stagenet-general-masteruser"
general_indexer_password = ""
transfers_indexer_url = "https://search-stagenet-transfer-vudkbsczrdiap4rsioqpxmkfke.us-east-2.es.amazonaws.com"
transfers_indexer_username = "stagenet-transfer-masteruser"
transfers_indexer_password = ""
environment = "stagenet"
api_gateway_integration_id = ""