##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|testnet-2]
log_level: debug # [debug|info]

external_api:
  endpoints:
    coingecko: "https://api.coingecko.com/api/v3/"
    ens: "https://api.thegraph.com/subgraphs/name/ensdomains/ens"

mainnet:
  agent: "axelarscan"
  endpoints:
    rpc: "https://rpc.axelarscan.io"
    lcd: "https://lcd.axelarscan.io"
    cli: "https://cli.axelarscan.io"
    api: "https://api.axelarscan.io"
    gmp_api: "https://api.gmp.axelarscan.io"
    app: "https://axelarscan.io"
    cosmostation: "https://api-axelar.cosmostation.io/v1"
    mintscan:
      api: "https://api.mintscan.io/v1/axelar"
      chain_id: "axelar-dojo-1"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_seconds: 300
  index_queue:
    min_index_round_count: 2
    max_index_round_count: 5
    concurrent_index_records: 10
    delay_ms_per_batch: 500
    max_records_synchronous: 200
  supply:
    max_supply: 1000000000
    initial_unlocked_percent: 2.5
    community_sale:
      total_unlock_percent: 2.5
      vesting_period: "month"
      vesting_start: "2022-09-27"
      vesting_until: "2023-01-27"
    community_programs:
      total_unlock_percent: 36
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    company_operations:
      total_unlock_percent: 12.5
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    backers:
      total_unlock_percent: 29.5
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2024-12-27"
    team:
      total_unlock_percent: 17
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2026-12-27"
  tvl:
    percent_diff_escrow_supply_threshold: 5.0
    percent_diff_total_supply_threshold: 5.0
    alert_asset_value_threshold: 3000000
  gateway:
    chains:
      ethereum:
        chain_id: 1
        endpoints:
          rpc:
            - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
            - "https://rpc.builder0x69.io"
            - "https://eth-mainnet.public.blastapi.io"
            - "https://1rpc.io/eth"
            - "https://rpc.ankr.com/eth"
      binance:
        chain_id: 56
        endpoints:
          rpc:
            - "https://bscrpc.com"
            - "https://bsc-mainnet.public.blastapi.io"
            - "https://1rpc.io/bnb"
            - "https://rpc.ankr.com/bsc"
      polygon:
        chain_id: 137
        endpoints:
          rpc:
            - "https://matic-mainnet.chainstacklabs.com"
            - "https://polygon-rpc.com"
            - "https://polygon-mainnet.public.blastapi.io"
            - "https://1rpc.io/matic"
            - "https://rpc.ankr.com/polygon"
      avalanche:
        chain_id: 43114
        endpoints:
          rpc:
            - "https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc"
            - "https://1rpc.io/avax/c"
            - "https://rpc.ankr.com/avalanche"
      fantom:
        chain_id: 250
        endpoints:
          rpc:
            - "https://rpcapi.fantom.network"
            - "https://rpc.ftm.tools"
            - "https://fantom-mainnet.public.blastapi.io"
            - "https://1rpc.io/ftm"
            - "https://rpc.ankr.com/fantom"
      moonbeam:
        chain_id: 1284
        endpoints:
          rpc:
            - "https://rpc.api.moonbeam.network"
            - "https://moonbeam.public.blastapi.io"
            - "https://1rpc.io/glmr"
            - "https://rpc.ankr.com/moonbeam"
      aurora:
        chain_id: 1313161554
        endpoints:
          rpc:
            - "https://mainnet.aurora.dev"
      arbitrum:
        chain_id: 42161
        endpoints:
          rpc:
            - "https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
            - "https://arb1.arbitrum.io/rpc"
            - "https://1rpc.io/arb"
            - "https://rpc.ankr.com/arbitrum"
      optimism:
        chain_id: 10
        endpoints:
          rpc:
            - "https://mainnet.optimism.io"
            - "https://optimism-mainnet.public.blastapi.io"
            - "https://1rpc.io/op"
            - "https://rpc.ankr.com/optimism"
      celo:
        chain_id: 42220
        endpoints:
          rpc:
            - "https://forno.celo.org"
            - "https://1rpc.io/celo"
            - "https://rpc.ankr.com/celo"
      kava:
        chain_id: 2222
        endpoints:
          rpc:
            - "https://evm.kava.io"
            - "https://evm2.kava.io"
    contracts:
      ethereum:
        address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
      binance:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      avalanche:
        address: "0x5029C0EFf6C34351a0CEc334542cDb22c7928f78"
      polygon:
        address: "0x6f015F16De9fC8791b234eF68D486d2bF203FBA8"
      fantom:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      moonbeam:
        address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
      aurora:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      arbitrum:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
      optimism:
        address: ""
      celo:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
      kava:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"



testnet:
  agent: "axelarscan"
  endpoints:
    rpc: "https://testnet.rpc.axelarscan.io"
    lcd: "https://testnet.lcd.axelarscan.io"
    cli: "https://testnet.cli.axelarscan.io"
    api: "https://testnet.api.axelarscan.io"
    gmp_api: "https://testnet.api.gmp.axelarscan.io"
    app: "https://testnet.axelarscan.io"
    cosmostation: "https://api-axelar-testnet.cosmostation.io/v1"
    mintscan:
      api: "https://api.mintscan.io/v1/axelar-testnet"
      chain_id: "axelar-testnet-lisbon-3"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_seconds: 300
  index_queue:
    min_index_round_count: 2
    max_index_round_count: 5
    concurrent_index_records: 10
    delay_ms_per_batch: 500
    max_records_synchronous: 200
  supply:
    max_supply: 1000000000
    initial_unlocked_percent: 0
    community_sale:
      total_unlock_percent: 0
      vesting_period: "month"
      vesting_start: "2022-09-27"
      vesting_until: "2023-01-27"
    community_programs:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    company_operations:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    backers:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2024-12-27"
    team:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2026-12-27"
  tvl:
    percent_diff_escrow_supply_threshold: 5.0
    percent_diff_total_supply_threshold: 5.0
    alert_asset_value_threshold: 3000000
  gateway:
    chains:
      ethereum-2:
        chain_id: 5
        endpoints:
          rpc:
            - "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
            - "https://eth-goerli.public.blastapi.io"
            - "https://rpc.ankr.com/eth_goerli"
      binance:
        chain_id: 97
        endpoints:
          rpc:
            - "https://data-seed-prebsc-1-s1.binance.org:8545"
            - "https://data-seed-prebsc-2-s1.binance.org:8545"
            - "https://data-seed-prebsc-1-s2.binance.org:8545"
            - "https://bsc-testnet.public.blastapi.io"
            - "https://rpc.ankr.com/bsc_testnet_chapel"
      polygon:
        chain_id: 80001
        endpoints:
          rpc:
            - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
            - "https://matic-mumbai.chainstacklabs.com"
            - "https://polygon-testnet.public.blastapi.io"
            - "https://rpc.ankr.com/polygon_mumbai"
      avalanche:
        chain_id: 43113
        endpoints:
          rpc:
            - "https://ava-testnet.public.blastapi.io/ext/bc/C/rpc"
            - "https://rpc.ankr.com/avalanche_fuji"
      fantom:
        chain_id: 4002
        endpoints:
          rpc:
            # - "https://fantom-testnet.public.blastapi.io"
            # - "https://rpc.testnet.fantom.network"
            - "https://rpc.ankr.com/fantom_testnet"
      moonbeam:
        chain_id: 1287
        endpoints:
          rpc:
            - "https://moonbase-alpha.public.blastapi.io"
            - "https://rpc.api.moonbase.moonbeam.network"
            - "https://rpc.testnet.moonbeam.network"
      aurora:
        chain_id: 1313161555
        endpoints:
          rpc:
            - "https://testnet.aurora.dev"
      arbitrum:
        chain_id: 421613
        endpoints:
          rpc:
            - "https://goerli-rollup.arbitrum.io/rpc"
            - "https://arb-goerli.g.alchemy.com/v2/demo"
      optimism:
        chain_id: 420
        endpoints:
          rpc:
            - "https://goerli.optimism.io"
            - "https://opt-goerli.g.alchemy.com/v2/demo"
            - "https://rpc.ankr.com/optimism_testnet"
      celo:
        chain_id: 44787
        endpoints:
          rpc:
            - "https://alfajores-forno.celo-testnet.org"
      kava:
        chain_id: 2221
        endpoints:
          rpc:
            - "https://evm.testnet.kava.io"
    contracts:
      ethereum-2:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
      binance:
        address: "0x4D147dCb984e6affEEC47e44293DA442580A3Ec0"
      avalanche:
        address: "0xC249632c2D40b9001FE907806902f63038B737Ab"
      polygon:
        address: "0xBF62ef1486468a6bd26Dd669C06db43dEd5B849B"
      fantom:
        address: "0x97837985Ec0494E7b9C71f5D3f9250188477ae14"
      moonbeam:
        address: "0x5769D84DD62a6fD969856c75c7D321b84d455929"
      aurora:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      arbitrum:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
      optimism:
        address: ""
      celo:
        address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
      kava:
        address: "0xC8D18F85cB0Cee5C95eC29c69DeaF6cea972349c"



testnet-2:
  endpoints:
    rpc: "https://testnet-2.rpc.axelarscan.io"
    lcd: "https://testnet-2.lcd.axelarscan.io"
    cli: "https://testnet-2.cli.axelarscan.io"
    api: "https://testnet-2.api.axelarscan.io"
    app: "https://testnet-2.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_seconds: 300
  index_queue:
    min_index_round_count: 1
    max_index_round_count: 3
    concurrent_index_records: 10
    delay_ms_per_batch: 2000
    max_records_synchronous: 300
  supply:
    max_supply: 1000000000
    initial_unlocked_percent: 0
    community_sale:
      total_unlock_percent: 0
      vesting_period: "month"
      vesting_start: "2022-09-27"
      vesting_until: "2023-01-27"
    community_programs:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    company_operations:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-09-27"
      vesting_until: "2026-09-27"
    backers:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2024-12-27"
    team:
      total_unlock_percent: 0
      vesting_period: "day"
      vesting_start: "2022-12-27"
      vesting_until: "2026-12-27"