#########################
# General Configuration #
#########################

mainnet:
  api: "https://lmfw5li4k2.execute-api.us-east-2.amazonaws.com"
  past_events_block_per_request: 100 # [1-500]
  max_query_events_block: 1000



testnet:
  api: "https://525fvkaztb.execute-api.us-east-2.amazonaws.com"
  past_events_block_per_request: 100 # [1-500]
  max_query_events_block: 1000