###########################
# Endpoints Configuration #
###########################

mainnet:
  rpc: "http://archive-node-rpc.axelarscan.io:80" # "http://ec2-18-218-242-252.us-east-2.compute.amazonaws.com:26657"
  lcd: "http://archive-node-lcd.axelarscan.io:80" # "http://ec2-18-218-242-252.us-east-2.compute.amazonaws.com:1317"
  api: "https://l4sytro3nf.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/api"
  gmp_api: "https://tlvaojpaa1.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/gmp"
  token_transfer_api: "https://kzb57uyt1b.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/token"
  validator_api: "https://k69t8uxsk1.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io/validator"
  app: "https://axelarscan.io"



testnet:
  rpc: "http://testnet.archive-node-rpc.axelarscan.io:80" # "http://ec2-18-188-23-105.us-east-2.compute.amazonaws.com:26657"
  lcd: "http://testnet.archive-node-lcd.axelarscan.io:80" # "http://ec2-18-188-23-105.us-east-2.compute.amazonaws.com:1317"
  api: "https://vup1csssf8.execute-api.us-east-2.amazonaws.com" # "https://testnet.api.axelarscan.io/api"
  gmp_api: "https://drfti3v7x2.execute-api.us-east-2.amazonaws.com" # "https://testnet.api.axelarscan.io/gmp"
  token_transfer_api: "https://jzrxbirmli.execute-api.us-east-2.amazonaws.com" # "https://testnet.api.axelarscan.io/token"
  validator_api: "https://gtiorun7sc.execute-api.us-east-2.amazonaws.com" # "https://testnet.api.axelarscan.io/validator"
  app: "https://testnet.axelarscan.io"



stagenet:
  rpc: "http://k8s-stagenet-axelarco-bcdb269e08-d3015352a090f6b0.elb.us-east-2.amazonaws.com:26657"
  lcd: "http://k8s-stagenet-axelarco-bcdb269e08-d3015352a090f6b0.elb.us-east-2.amazonaws.com:1317"
  api: "https://l49zjsjm3f.execute-api.us-east-2.amazonaws.com" # "https://stagenet.api.axelarscan.io/api"
  gmp_api: "https://8mcrlxwctd.execute-api.us-east-2.amazonaws.com" # "https://stagenet.api.axelarscan.io/gmp"
  token_transfer_api: "https://4vabxwwr0d.execute-api.us-east-2.amazonaws.com" # "https://stagenet.api.axelarscan.io/token"
  validator_api: "https://ghv17z2lli.execute-api.us-east-2.amazonaws.com" # "https://stagenet.api.axelarscan.io/validator"
  app: "https://stagenet.axelarscan.io"