############################
# ITS Assets Configuration #
############################

mainnet:
  -
    symbol: "RMRK"
    image: "/logos/its/rmrk.svg"
    coingecko_id: "rmrk"
    addresses:
      - "0x524d524B4c9366be706D3A90dcf70076ca037aE3"



testnet:



stagenet: