############################
# ITS Assets Configuration #
############################

mainnet:
  -
    symbol: "RMRK"
    decimals: 18
    image: "/logos/its/rmrk.svg"
    coingecko_id: "rmrk"
    addresses:
      - "0x524d524B4c9366be706D3A90dcf70076ca037aE3"
      - "0x7e5738bDabc8ADb3670b07eA0e7D4b0B94282E4f"



testnet:



stagenet: