###########################
# API methods Information #
###########################

endpoints:
  mainnet: "https://api.axelarscan.io"
  testnet: "https://testnet.api.axelarscan.io"
  stagenet: "https://stagenet.api.axelarscan.io/api"
methods:
  -
    id: "getChains"
    description: "The API route provides all chains information supported on the Axelar network."
    response:
      -
        name: "data"
        type: "[object]"
        primitive: true
        attributes:
          -
            name: "id"
            type: "string"
            description: "ID using in general purpose"
          -
            name: "chain_id"
            type: "integer/string"
            description: "chain identifier for EVM/Cosmos chain (number for EVM, string for Cosmos)"
          -
            name: "chain_name"
            type: "string"
            description: "specific name for using in axelar"
          -
            name: "maintainer_id"
            type: "string"
            description: "identifier of each EVM chain that axelar use for transaction confirmation (for validator)"
          -
            name: "endpoints"
            type: "object"
            description: "chain's endpoints for retrieving on chain data"
            attributes:
              -
                name: "rpc"
                type: "[string]"
                description: "list of RPC provider"
              -
                name: "lcd"
                type: "[string]"
                description: "list of LCD provider"
          -
            name: "native_token"
            type: "object"
            description: "native token info"
            attributes:
              -
                name: "symbol"
                type: "string"
              -
                name: "name"
                type: "string"
              -
                name: "decimals"
                type: "integer"
          -
            name: "name"
            type: "string"
            description: "display name"
          -
            name: "short_name"
            type: "string"
            description: "shorter name for display"
          -
            name: "image"
            type: "string"
            description: "logo path"
          -
            name: "color"
            type: "string"
            description: "RGB hex color"
          -
            name: "explorer"
            type: "object"
            description: "chain explorer info"
            attributes:
              -
                name: "name"
                type: "string"
              -
                name: "url"
                type: "string"
                description: "base URL"
              -
                name: "icon"
                type: "string"
                description: "logo path"
              -
                name: "block_path"
                type: "string"
              -
                name: "address_path"
                type: "string"
              -
                name: "contract_path"
                type: "string"
              -
                name: "contract_0_path"
                type: "string"
                description: "path of ZeroAddress"
              -
                name: "transaction_path"
                type: "string"
              -
                name: "asset_path"
                type: "string"
                description: "asset path for each denom on mintscan explorer"
          -
            name: "prefix_address"
            type: "string"
            description: "prefix string of address"
          -
            name: "prefix_chain_ids"
            type: "[string]"
            description: "prefix string of cosmos chain ID"
          -
            name: "chain_type"
            type: "string"
            description: "type of chain (evm/cosmos)"
          -
            name: "provider_params"
            type: "[object]"
            description: "parameters for EVM wallet connection"
  -
    id: "getAssets"
    description: "The API route provides all assets information supported on the Axelar network."
    response:
      -
        name: "data"
        type: "[object]"
        primitive: true
        attributes:
          -
            name: "id"
            type: "string"
            description: "ID using in general purpose"
          -
            name: "denom"
            type: "string"
          -
            name: "native_chain"
            type: "string"
            description: "general ID of chain that asset in native on"
          -
            name: "name"
            type: "string"
            description: "display name"
          -
            name: "symbol"
            type: "string"
          -
            name: "decimals"
            type: "integer"
            description: "token decimals"
          -
            name: "image"
            type: "string"
            description: "logo path"
          -
            name: "coingecko_id"
            type: "string"
            description: "asset identifier on coingecko service"
          -
            name: "addresses"
            type: "Map"
            description: "asset's address lookup by chain ([chain, token])"
            attributes:
              -
                type: "entry"
                key: "chain"
                value:
                  type: "object"
                  attributes:
                    -
                      name: "address"
                      type: "string"
                      description: "EVM token address"
                    -
                      name: "ibc_denom"
                      type: "string"
                      description: "Cosmos token address (denom)"
                    -
                      name: "symbol"
                      type: "string"
                      description: "symbol of asset on each chain"
  -
    id: "getContracts"
    description: "The API route provides a list of Axelar gateway and the Gas Service contract addresses on each EVM-supported chain."
    response:
      -
        name: "gateway_contracts"
        type: "Map"
        description: "gateway's address lookup by chain ([chain, contract])"
        attributes:
          -
            type: "entry"
            key: "chain"
            value:
              type: "object"
              attributes:
                -
                  name: "address"
                  type: "string"
      -
        name: "gas_service_contracts"
        type: "Map"
        description: "gas service's address lookup by chain ([chain, contract])"
        attributes:
          -
            type: "entry"
            key: "chain"
            value:
              type: "object"
              attributes:
                -
                  name: "address"
                  type: "string"
      -
        name: "operators_contracts"
        type: "Map"
        description: "operator contract's address lookup by chain ([chain, contract])"
        attributes:
          -
            type: "entry"
            key: "chain"
            value:
              type: "object"
              attributes:
                -
                  name: "address"
                  type: "string"
  -
    id: "getTokensPrice"
    description: "The API route provides price of asset."
    parameters:
      -
        name: "symbol"
        type: "string"
        description: "symbol/denom to get price (can get multiple by [string] or string with delimiter ',')"
        required: true
      -
        name: "timestamp"
        type: "long"
        description: "price at timestamp (in milliseconds)"
    response:
      -
        type: "Map"
        description: "asset info lookup by symbol ([symbol, token])"
        attributes:
          -
            type: "entry"
            key: "symbol"
            value:
              type: "object"
              attributes:
                -
                  name: "price"
                  type: "float"
                -
                  name: "decimals"
                  type: "integer"
                -
                  name: "symbol"
                  type: "string"
                -
                  name: "coingecko_id"
                  type: "string"
                  description: "asset identifier on coingecko service"
  -
    id: "getTotalSupply"
    description: "The API route provides information of the total supply of the Axelar Network."
    response:
      -
        name: "value"
        type: "float"
        description: "total supply"
        primitive: true
  -
    id: "getCirculatingSupply"
    description: "The API route provides information of the circulating supply of the Axelar Network."
    parameters:
      -
        name: "symbol"
        type: "string"
        default: "AXL"
    response:
      -
        name: "value"
        type: "float"
        description: "circulating supply"
        primitive: true
  -
    id: "getTokenInfo"
    description: "The API route provides the token supply-related information of the AXL token."
    parameters:
      -
        name: "symbol"
        type: "string"
        default: "AXL"
    response:
      -
        name: "symbol"
        type: "string"
      -
        name: "name"
        type: "string"
        description: "display name"
      -
        name: "price"
        type: "float"
        description: "token price in dollar"
      -
        name: "marketCap"
        type: "float"
        description: "value of circulating supply"
      -
        name: "circulatingSupply"
        type: "float"
        description: "current supply of this token"
      -
        name: "maxSupply"
        type: "float"
      -
        name: "updatedAt"
        type: "long"
        description: "updated time (in milliseconds)"
  -
    id: "getInflation"
    description: "The API route provides information of the inflation rate in the Axelar Network."
    response:
      -
        name: "equation"
        type: "string"
        description: "how to calculate inflation"
      -
        name: "tendermintInflationRate"
        type: "float"
      -
        name: "communityTax"
        type: "float"
      -
        name: "keyMgmtRelativeInflationRate"
        type: "float"
      -
        name: "externalChainVotingInflationRate"
        type: "float"
      -
        name: "uptimeRate"
        type: "float"
      -
        name: "heartbeatRate"
        type: "float"
      -
        name: "numEVMChains"
        type: "integer"
      -
        name: "inflation"
        type: "float"
  -
    id: "interchainChart"
    description: "The API route provides the number of interchain activities for each day in a specific timeframe."
    parameters:
      -
        name: "sourceChain"
        type: "string"
      -
        name: "destinationChain"
        type: "string"
      -
        name: "fromTime"
        type: "unixtime"
      -
        name: "toTime"
        type: "unixtime"
    response:
      -
        name: "data"
        type: "[object]"
        description: "chart data of GMP by time"
        attributes:
          -
            name: "timestamp"
            type: "long"
            description: "timestamp in milliseconds as a key of each bar"
          -
            name: "num_txs"
            type: "integer"
            description: "number of transactions"
          -
            name: "volume"
            type: "float"
            description: "transaction volume"
          -
            name: "fee"
            type: "float"
            description: "transaction fee"
          -
            name: "users"
            type: "integer"
            description: "number of users"
          -
            name: "gmp_num_txs"
            type: "integer"
            description: "number of GMP transactions"
          -
            name: "gmp_volume"
            type: "float"
            description: "GMP transaction volume"
          -
            name: "gmp_fee"
            type: "float"
            description: "GMP transaction fee"
          -
            name: "gmp_users"
            type: "integer"
            description: "number of users using GMP"
          -
            name: "transfers_num_txs"
            type: "integer"
            description: "number of token transfers transactions"
          -
            name: "transfers_volume"
            type: "float"
            description: "token transfers transaction volume"
          -
            name: "transfers_fee"
            type: "float"
            description: "token transfers transaction fee"
          -
            name: "transfers_users"
            type: "integer"
            description: "number of users using token transfers"
  -
    id: "interchainTotalVolume"
    description: "The API route provides the total volume of the interchain activities through the Axelar network."
    parameters:
      -
        name: "sourceChain"
        type: "string"
      -
        name: "destinationChain"
        type: "string"
      -
        name: "fromTime"
        type: "unixtime"
      -
        name: "toTime"
        type: "unixtime"
    response:
      -
        name: "value"
        type: "float"
        description: "total volume"
        primitive: true
  -
    id: "interchainTotalFee"
    description: "The API route provides the total fee of the interchain activities through the Axelar network."
    parameters:
      -
        name: "sourceChain"
        type: "string"
      -
        name: "destinationChain"
        type: "string"
      -
        name: "fromTime"
        type: "unixtime"
      -
        name: "toTime"
        type: "unixtime"
    response:
      -
        name: "value"
        type: "float"
        description: "total fee"
        primitive: true
  -
    id: "interchainTotalActiveUsers"
    description: "The API route provides the total active users of the interchain activities through the Axelar network."
    parameters:
      -
        name: "sourceChain"
        type: "string"
      -
        name: "destinationChain"
        type: "string"
      -
        name: "fromTime"
        type: "unixtime"
      -
        name: "toTime"
        type: "unixtime"
    response:
      -
        name: "value"
        type: "integer"
        description: "total active users"
        primitive: true
  -
    id: "getTVL"
    description: "The API route provides the latest total volume locked (TVL) on the Axelar network, separated by assets."
    parameters:
      -
        name: "asset"
        type: "string"
        description: "asset denom"
        required: true
        default: "uaxl"
    response:
      -
        name: "data"
        type: "[object]"
        description: "TVL data of asset"
        attributes:
          -
            name: "asset"
            type: "string"
            description: "asset denom from parameters"
          -
            name: "total"
            type: "float"
            description: "total supply locked on Axelar network"
          -
            name: "total_on_evm"
            type: "float"
            description: "total wrapped supply moved to EVM chains"
          -
            name: "total_on_cosmos"
            type: "float"
            description: "total wrapped supply moved to Cosmos chains"
          -
            name: "price"
            type: "float"
            description: "token price in dollar"
          -
            name: "percent_diff_supply"
            type: "float"
            description: "percentage of the supply different between (total on evm + total on cosmos) / total"
          -
            name: "is_abnormal_supply"
            type: "boolean"
            description: "anomaly flag"