#########################
# General Configuration #
#########################

mainnet:
  api: "https://lmfw5li4k2.execute-api.us-east-2.amazonaws.com" # "https://api.axelarscan.io"
  ws: "ws://archive-node-rpc.axelarscan.io:80" # "ws://ec2-18-218-242-252.us-east-2.compute.amazonaws.com:26657"  
  reindex:
    enable: false
    start_block: 6500000
    end_block: 7000000
    num_processes: 2



testnet:
  api: "https://525fvkaztb.execute-api.us-east-2.amazonaws.com" # "https://testnet.api.axelarscan.io"
  ws: "ws://testnet.archive-node-rpc.axelarscan.io:80" # "ws://ec2-18-188-23-105.us-east-2.compute.amazonaws.com:26657"
  reindex:
    enable: false
    start_block: 7000000
    end_block: 7500000
    num_processes: 2



stagenet:
  api: "https://9d7cqdtnme.execute-api.us-east-2.amazonaws.com" # "https://stagenet.api.axelarscan.io"
  ws: "ws://k8s-stagenet-axelarco-bcdb269e08-d3015352a090f6b0.elb.us-east-2.amazonaws.com:26657"
  reindex:
    enable: false
    start_block: 0
    end_block: 260000
    num_processes: 2