##################################
# RPCs & Contracts Configuration #
##################################

mainnet:
  api: "https://api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum:
      chain_id: 1
      endpoints:
        rpc:
          - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.builder0x69.io"
          - "https://eth-mainnet.public.blastapi.io"
          - "https://1rpc.io/eth"
          - "https://rpc.ankr.com/eth"
    binance:
      chain_id: 56
      endpoints:
        rpc:
          - "https://bsc-dataseed.binance.org"
          - "https://bsc-dataseed1.ninicoin.io"
          - "https://bsc-dataseed1.defibit.io"
          - "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3"
          - "https://bsc-mainnet.public.blastapi.io"
          - "https://1rpc.io/bnb"
          - "https://bscrpc.com"
          - "https://rpc.ankr.com/bsc"
    polygon:
      chain_id: 137
      endpoints:
        rpc:
          - "https://polygon-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://matic-mainnet.chainstacklabs.com"
          - "https://poly-rpc.gateway.pokt.network"
          - "https://polygon.blockpi.network/v1/rpc/public"
          - "https://polygon-mainnet.public.blastapi.io"
          - "https://1rpc.io/matic"
          - "https://rpc.ankr.com/polygon"
    avalanche:
      chain_id: 43114
      endpoints:
        rpc:
          - "https://avalanche.blockpi.network/v1/rpc/public"
          - "https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc"
          - "https://1rpc.io/avax/c"
          - "https://rpc.ankr.com/avalanche"
    fantom:
      chain_id: 250
      endpoints:
        rpc:
          - "https://rpc.ftm.tools"
          - "https://rpc.fantom.network"
          - "https://fantom.blockpi.network/v1/rpc/public"
          - "https://fantom-mainnet.public.blastapi.io"
          - "https://1rpc.io/ftm"
          - "https://rpc.ankr.com/fantom"
    moonbeam:
      chain_id: 1284
      endpoints:
        rpc:
          - "https://rpc.api.moonbeam.network"
          - "https://moonbeam.public.blastapi.io"
          - "https://1rpc.io/glmr"
          - "https://rpc.ankr.com/moonbeam"
    aurora:
      chain_id: 1313161554
      endpoints:
        rpc:
          - "https://mainnet.aurora.dev"
    arbitrum:
      chain_id: 42161
      endpoints:
        rpc:
          - "https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://arbitrum.blockpi.network/v1/rpc/public"
          - "https://arb1.arbitrum.io/rpc"
          - "https://1rpc.io/arb"
          - "https://rpc.ankr.com/arbitrum"
    optimism:
      chain_id: 10
      endpoints:
        rpc:
          - "https://optimism-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://optimism.blockpi.network/v1/rpc/public"
          - "https://optimism-mainnet.public.blastapi.io"
          - "https://1rpc.io/op"
          - "https://rpc.ankr.com/optimism"
    base:
      chain_id: 8453
      endpoints:
        rpc:
          - ""
    celo:
      chain_id: 42220
      endpoints:
        rpc:
          - "https://forno.celo.org"
          - "https://1rpc.io/celo"
          - "https://rpc.ankr.com/celo"
    kava:
      chain_id: 2222
      endpoints:
        rpc:
          - "https://evm.data.axelar.kava.io"
          # - "https://evm.kava.io"
          # - "https://evm2.kava.io"
    filecoin:
      chain_id: 314
      endpoints:
        rpc:
          - "https://rpc.ankr.com/filecoin"
          - "https://api.node.glif.io"
  gateway_contracts:
    ethereum:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    binance:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    avalanche:
      address: "0x5029C0EFf6C34351a0CEc334542cDb22c7928f78"
    polygon:
      address: "0x6f015F16De9fC8791b234eF68D486d2bF203FBA8"
    fantom:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    moonbeam:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    arbitrum:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    optimism:
      address: ""
    base:
      address: ""
    celo:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    kava:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    filecoin:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"



testnet:
  api: "https://testnet.api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum-2:
      chain_id: 5
      endpoints:
        rpc:
          - "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://eth-goerli.public.blastapi.io"
          - "https://rpc.ankr.com/eth_goerli"
    binance:
      chain_id: 97
      endpoints:
        rpc:
          - "https://data-seed-prebsc-1-s1.binance.org:8545"
          - "https://data-seed-prebsc-2-s1.binance.org:8545"
          - "https://data-seed-prebsc-1-s2.binance.org:8545"
          - "https://bsc-testnet.public.blastapi.io"
          - "https://rpc.ankr.com/bsc_testnet_chapel"
    polygon:
      chain_id: 80001
      endpoints:
        rpc:
          - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://matic-mumbai.chainstacklabs.com"
          - "https://polygon-testnet.public.blastapi.io"
          - "https://rpc.ankr.com/polygon_mumbai"
    avalanche:
      chain_id: 43113
      endpoints:
        rpc:
          - "https://ava-testnet.public.blastapi.io/ext/bc/C/rpc"
          - "https://api.avax-test.network/ext/bc/C/rpc"
          - "https://rpc.ankr.com/avalanche_fuji"
    fantom:
      chain_id: 4002
      endpoints:
        rpc:
          - "https://fantom-testnet.public.blastapi.io"
          - "https://rpc.testnet.fantom.network"
          - "https://rpc.ankr.com/fantom_testnet"
    moonbeam:
      chain_id: 1287
      endpoints:
        rpc:
          - "https://moonbase-alpha.public.blastapi.io"
          - "https://rpc.api.moonbase.moonbeam.network"
          - "https://rpc.testnet.moonbeam.network"
    aurora:
      chain_id: 1313161555
      endpoints:
        rpc:
          - "https://testnet.aurora.dev"
    arbitrum:
      chain_id: 421613
      endpoints:
        rpc:
          - "https://goerli-rollup.arbitrum.io/rpc"
          - "https://endpoints.omniatech.io/v1/arbitrum/goerli/public"
    optimism:
      chain_id: 420
      endpoints:
        rpc:
          - "https://optimism-goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/optimism_testnet"
    base:
      chain_id: 84531
      endpoints:
        rpc:
          - "https://goerli.base.org"
    celo:
      chain_id: 44787
      endpoints:
        rpc:
          - "https://alfajores-forno.celo-testnet.org"
    kava:
      chain_id: 2221
      endpoints:
        rpc:
          - "https://evm.testnet.kava.io"
    filecoin:
      chain_id: 3141
      endpoints:
        rpc:
          - "https://rpc.ankr.com/filecoin_testnet"
          - "https://api.hyperspace.node.glif.io/rpc/v1"
  gateway_contracts:
    ethereum-2:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    binance:
      address: "0x4D147dCb984e6affEEC47e44293DA442580A3Ec0"
    avalanche:
      address: "0xC249632c2D40b9001FE907806902f63038B737Ab"
    polygon:
      address: "0xBF62ef1486468a6bd26Dd669C06db43dEd5B849B"
    fantom:
      address: "0x97837985Ec0494E7b9C71f5D3f9250188477ae14"
    moonbeam:
      address: "0x5769D84DD62a6fD969856c75c7D321b84d455929"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    arbitrum:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    optimism:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    base:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    celo:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    kava:
      address: "0xC8D18F85cB0Cee5C95eC29c69DeaF6cea972349c"
    filecoin:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"