##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet]
port:
  cli: 3333
log_level: debug # [debug|info]

mainnet:
  endpoints:
    ws: "ws://ws.axelarscan.io"
    api: "https://api.axelarscan.io"
  num_prev_blocks_fetch_tx: 2
  num_reindex_processes: 2
  start_reindex_block: 1
  end_reindex_block: 5000000
  reindex: false

testnet:
  endpoints:
    ws: "ws://testnet.ws.axelarscan.io"
    api: "https://testnet.api.axelarscan.io"
  num_prev_blocks_fetch_tx: 2
  num_reindex_processes: 2
  start_reindex_block: 690489
  end_reindex_block: 5000000
  reindex: false